src/Core/FileServerBundle/Entity/File.php
<?php

namespace Core\FileServerBundle\Entity;


use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

use Doctrine\ORM\Mapping as ORM;

/**
 * File
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Core\FileServerBundle\Entity\FileRepository")
 */
class File
{

    public function removeAllPermissions()
    {
        foreach ($this->permissions as $p) {
            $this->removePermission($p);
        }
    }

    //RELATIONS

    /**
     * @ORM\ManyToOne(targetEntity="\Core\UserBundle\Entity\User", inversedBy="files")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @ORM\OneToMany(targetEntity="Permissions", mappedBy="file")
     */
    private $permissions;


    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var boolean
     *
     * @ORM\Column(name="public", type="boolean")
     *
     * publico para todos mis clientes
     */
    private $public;

    /**
     * @var string
     *
     * @ORM\Column(name="hash", type="string")
     */
    private $hash;
    /**
     * @var string
     *
     * @ORM\Column(name="mime", type="string")
     */
    private $mime;

    /**
     * @var integer
     *
     * @ORM\Column(name="size", type="integer")
     *
     * size in Kb
     */
    private $size;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    //File
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $path;

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir() . '/' . $this->path;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir() . '/' . $this->path;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../../../security/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/documents';
    }

    public function upload($file)
    {
        if (null === $this->file) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $old = $this->path;
        $this->hash = uniqid();
        $this->size = $file->getSize();
        $this->mime = $file->getMimeType();
        $file->move($this->getUploadRootDir(), $file->getBasename());
        //rename($file->getRealPath(), __DIR__.$this->getUploadRootDir()."/".$file->getBasename());
        //$this->file->move($this->getUploadRootDir(), $this->path);


        $this->file = null;
    }


    private $file;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile($file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    public function getMimeHuman()
    {

        $chunks = explode("/", $this->mime);
        switch ($chunks[0]) {

            default:
                return "unknown";
                break;

            case "video":
                return 'video';
                break;

            case 'image':
                return 'image';
                break;

            case 'audio':
                return 'audio';
                break;

            case 'application':
                if ($chunks[1] == 'pdf') {
                    return 'pdf';
                } else {
                    return "unknown";
                }

        }
    }

    ///
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return File
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }


    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return File
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->permissions = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set path
     *
     * @param string $path
     * @return File
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set owner
     *
     * @param \Core\UserBundle\Entity\User $owner
     * @return File
     */
    public function setOwner(\Core\UserBundle\Entity\User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner
     *
     * @return \Core\UserBundle\Entity\User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Add permissions
     *
     * @param \Core\FileServerBundle\Entity\Permissions $permissions
     * @return File
     */
    public function addPermission(\Core\FileServerBundle\Entity\Permissions $permissions)
    {
        $this->permissions[] = $permissions;

        return $this;
    }


    /**
     * Remove permissions
     *
     * @param \Core\FileServerBundle\Entity\Permissions $permissions
     */
    public function removePermission(\Core\FileServerBundle\Entity\Permissions $permissions)
    {
        $this->permissions->removeElement($permissions);
    }

    /**
     * Get permissions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Set public
     *
     * @param boolean $public
     * @return File
     */
    public function setPublic($public)
    {
        $this->public = $public;

        return $this;
    }

    /**
     * Get public
     *
     * @return boolean
     */
    public function getPublic()
    {
        return $this->public;
    }

    /**
     * Set hash
     *
     * @param string $hash
     * @return File
     */
    public function setHash($hash)
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * Get hash
     *
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Set size
     *
     * @param integer $size
     * @return File
     */
    public function setSize($size)
    {
        $this->size = $size;

        return $this;
    }

    /**
     * Get size
     *
     * @return integer
     */
    public function getSize()
    {
        return $this->size;
    }

    public function getSizeHum()
    {
        $kb = $this->size / 1000;

        return $kb . " Kb";
    }

    /**
     * Set mime
     *
     * @param string $mime
     * @return File
     */
    public function setMime($mime)
    {
        $this->mime = $mime;

        return $this;
    }

    /**
     * Get mime
     *
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }


}

src/Core/FileServerBundle/Controller/DefaultController.php
<?php

namespace Core\FileServerBundle\Controller;

use Core\FileServerBundle\Entity\File;
use Core\FileServerBundle\Entity\Permissions;
use Core\FileServerBundle\Form\FileType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Response;


class DefaultController extends Controller
{
    public function indexAction($name)
    {
        return $this->render('CoreFileServerBundle:Default:index.html.twig', array('name' => $name));
    }


    /**
     * @Route("/core/downloader/{hash}", name="core_fileserver_downloader", defaults={ "hash" = "none" })
     * @Template()
     *
     * devuelvo el formulario para subir archivos
     */
    public function downloadAction($hash)
    {
        $me = $this->get('security.context')->getToken()->getUser();
        //busco el archivo
        if(empty($me)){
            throw new \Exception('You must be logged in');
        }


        $file = $this->getDoctrine()->getManager()->getRepository('CoreFileServerBundle:File')->findOneByHash($hash);

        if(empty($file)){
           throw new \Exception('No file found');
        }

        $val = false;

        //compruebo si tengo acceso al archivo

        $qb = $this->getDoctrine()->getManager()
                    ->createQuery("SELECT p FROM CoreFileServerBundle:Permissions p WHERE p.user = :user AND p.permission >= :permissions AND p.file = :file")
                    ->setParameter('user', $me->getId())
                    ->setParameter('file', $file->getId())
                    ->setParameter('permissions', 4);


        $permissions = $qb->getResult();

        //Compruebo los permisos
        if(count($permissions) > 0){
            $val = true;
        }

        //el archivo es publico
        if($file->getPublic()){
            $val = true;
        }

        if($file->getOwner()->getId() == $me->getId()){//el archivo es mio
            $val = true;
        }

        if(!$val){
            throw new \Exception('You dont`t have access');
        }

        $options = array(
            'absolute_path' => true,
            'inline' => false,
        );

        $response = $this->get('igorw_file_serve.response_factory')
            ->create($file->getAbsolutePath(), 'text/plain', $options);

        return $response;

    }


    /**
     * @Route("/core/uploader/{idUser}/{redirect}", name="core_fileserver_uploader", defaults={ "redirect" = "none", "idUser" = "0" })
     * @Template()
     *
     * devuelvo el formulario para subir archivos
     */
    public function uploaderAction($idUser,$redirect)
    {

        $me = $this->get('security.context')->getToken()->getUser();
        $file = new File();

        $file->setCreatedAt(new \DateTime());

        if($me->hasRole('ROLE_CLIENTE')){
            //es un cliente, el owner es mi profesional
            $own = $me->getClient()->getProfessional()->getUser();
            $file->setOwner($own);
        }else{
            $file->setOwner($me);
        }



        if($idUser > 0){
            //añadimos un usuario como permiso
            $permission = new Permissions();
            $permission->setFile($file);
            $permission->setUser($idUser);

            $file->addPermission($permission);
        }


        $form = $this->createForm(new FileType(), $file);

        $request = $this->getRequest();

        if($request->getMethod() == 'POST'){


            $form->bind($request);
            if($form->isValid()){

                foreach($file->getPermissions() as $p){
                    $p->setCreatedAt(new \DateTime());
                    $p->setFile($file);

                    $file->addPermission($p);

                    $this->getDoctrine()->getManager()->persist($p);
                }

                if ($handle = $file->getFile()) {


                    $file->setPath($handle->getBasename());
                    $file->upload($handle);


                }

                $this->getDoctrine()->getManager()->persist($file);
                $this->getDoctrine()->getManager()->flush();

                //return new Response('Ok');

                if(is_null($redirect)){
                    $redirect = $request->get('redirect');
                }
                //

                if($redirect == 'ajax' OR $redirect == 'none'){
                    return new Response('Ok');
                }else{

                    return $this->redirect($this->generateUrl($redirect));
                }

            }else{
                print_r($form->getErrors());
            }
        }


        return array('form' => $form->createView(), 'redirect' => $redirect);


    }

    /**
     * @Route("/core/listfiles/{idUser}", name="core_fileserver_listfiles", defaults={ "idUser" = "0" })
     * @Template()
     *
     * devuelvo el formulario para subir archivos
     */
    public function listfilesAction($idUser)
    {

            $em = $this->getDoctrine()->getManager();

            $user = $em->getRepository('CoreUserBundle:User')->find($idUser);

        $qb = $em
            ->createQuery("SELECT p, f FROM CoreFileServerBundle:Permissions p LEFT JOIN p.file f WHERE p.user = :user AND p.permission >= :permissions")
            ->setParameter('user', $user->getId())
            ->setParameter('permissions', 4);

        $result = $qb->getResult();

        $files = array();
        foreach($result as $r){
            array_push($files, $r->getFile());
        }



        return array('files' => $files);
    }
}

src/Core/FileServerBundle/Resources/views/Default/fileadmin.html.twig
Nombre {{ file.title }}

<div class="well body">aisss</div>

src/Core/FileServerBundle/Resources/views/Default/index.html.twig
Hello {{ name }}!

src/Core/FileServerBundle/Resources/views/Default/listfiles.html.twig
<style>
    .icons-files i {
        font-size: 50px;
        padding: 5px;

    }

    .download-icon a {
        color: #555;
    }

    .download-icon a:hover {
        color: #8b0000;
    }

    .download-icon a i {
        font-size: 50px;
        padding: 5px;

    }
</style>

<h5 class="widget-name">
    <i class="icon-table"></i> Mis archivos
</h5>

<div class="widget">
    <div class="table-overflow">
        {% if files is not empty %}
            <table class="table table-striped table-bordered table-checks media-table dataTable" id="data-table"
                   aria-describedby="data-table_info">
                <thead>
                <tr role="row">
                    <th class="sorting_disabled" width="40px" style="text-align: center">Tipo</th>
                    <th class="sorting_disabled">Nombre</th>
                    <th class="sorting_disabled" width="30%">Información</th>
                    <th class="sorting_disabled" width="40px" style="text-align: center">Acciones</th>
                </tr>
                </thead>
                <tbody ole="alert" aria-live="polite" aria-relevant="all">
                {% for file in files %}
                    <tr class="{% if loop.index is odd %}odd{% else %}even{% endif %}">
                        <td class="icons-files">

                            {% if file.mimeHuman == 'audio' %}<i class="icon icon-volume-up"></i> {% endif %}
                            {% if file.mimeHuman == 'image' %}<i class="icon icon-picture"></i> {% endif %}
                            {% if file.mimeHuman == 'video' %}<i class="icon icon-facetime-video"></i> {% endif %}
                            {% if file.mimeHuman == 'pdf' %}<i class="icon icon-file"></i> {% endif %}
                            {% if file.mimeHuman == 'unknown' %}<i class="icon icon-ban-circle"></i> {% endif %}


                        </td>
                        <td class=" ">{{ file.title }}</td>
                        <td class="file-info">
                            <span><strong>Tamaño:</strong> {{ file.sizeHum }}</span>
                                <span><strong>Tipo de
                                        acceso:</strong> {% if file.public %}Acceso público{% else %}Acceso restringido{% endif %}</span>
                            <span><strong>Fecha de creacion:</strong> {{ file.createdAt|date('d-m-Y') }}</span>
                        </td>
                        <td class="download-icon ">

                            <a href="{{ path('core_fileserver_downloader', { 'hash': file.hash }) }}"
                               class="btn tip" title="" data-original-title="Descargar"><i
                                        class="icon-download-alt"></i></a>

                            <!--<li><a href="/app_dev.php/profesional/clientes/show/1" class="tip" title="" data-original-title="Editar Perfil"><i class="icon-cog"></i></a></li>-->

                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>
        {% else %}

            <h4>No tienes ficheros registrados</h4>
        {% endif %}
    </div>
</div>

<script type="text/javascript"
        src="{{ asset('bundles/coreresources/admintheme/js/plugins/tables/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript">
    $(function () {
        $('#data-table').dataTable({
            "bJQueryUI": false,
            "bAutoWidth": false,
            "sPaginationType": "full_numbers",
            "sDom": '<"datatable-header"fl>t<"datatable-footer"ip>',
            "oLanguage": {
                "sSearch": "<span>Filtro de búsqueda:</span> _INPUT_",
                "sLengthMenu": "<span>Número de entradas a mostrar:</span> _MENU_",
                "oPaginate": { "sFirst": "Inicio", "sLast": "Fin", "sNext": ">", "sPrevious": "<" }
            }
        });
    });
</script>

src/Core/FileServerBundle/Resources/views/Default/uploader.html.twig
{% form_theme form 'CoreResourcesBundle:Form:fields.html.twig' %}
<link href="{{ asset('bundles/coreresources/select2/select2.css') }}" rel="stylesheet" />
{{ form_stylesheet(form) }}

<script src="{{ asset('bundles/coreresources/select2/select2.js') }}"></script>
<script src="{{ asset('bundles/coreresources/select2/select2_locale_es.js') }}"></script>


<div id="content_uploader">
  {% if redirect == 'ajax' %}
      <script src="http://malsup.github.com/jquery.form.js"></script>
  {% endif %}
    <script type="text/javascript"
            src="{{ asset('bundles/coreresources/uploadify/jquery.uploadify.min.js') }}"></script>
    <link href="{{ asset('bundles/coreresources/uploadify/uploadify.css') }}" rel="stylesheet">


    {{ form_stylesheet(form) }}
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            var $field = $('#core_fileserverbundle_filetype_file_upload');
            var $form = $field.closest('form');
            var $queue = $('#core_fileserverbundle_filetype_file_queue');
            var $nbQueue = 0;


            var $configs = $.extend({
                "script": "genemu_upload",
                "swf": "\/bundles\/coreresources\/uploadify\/uploadify.swf",
                "cancelImg": "\/bundles\/genemuform\/images\/cancel.png",
                "folder": "\/upload",
                "auto": true,
                "multi": false,
                "uploader": "\/app_dev.php\/genemu_upload",
                "queueID": "core_fileserverbundle_filetype_file_queue",
                "removeCompleted": false
            }, {
                onUploadSuccess: function (file, data, response) {
                    data = jQuery.parseJSON(data);

                    if (data.result == '1') {
                        var value = data.file;

                        $('#core_fileserverbundle_filetype_file').val(value);
                        $nbQueue--;

                        $("#core_fileserverbundle_filetype_file_upload").css('display', 'none');
                        //$("#button_upload_file").css('visibility', 'visible');

                    } else {
                        alert('Error');
                    }
                },
                onSelect: function (file) {
                    $nbQueue++;
                },
                onUploadError: function (file, errorCode, errorMsg, errorString) {
                    alert('error');
                }
            });

            $form.submit(function (event) {
                return $joinFiles();
            });

            var $joinFiles = function () {
                if ($files = $field.data('files')) {
                    $field.val($files.join(','));
                }

                return true;
            }

            $field.uploadify($configs);
        });
    </script>

    <form id="form_upload" method="post" {{ form_enctype(form) }}
          action="{{ path('core_fileserver_uploader', {'redirect': redirect}) }}">
        <fieldset>
            <div class="widget row-fluid">
                <div class="well">
                    {{ form_row(form.title) }}
                    {{ form_row(form.public) }}
                    {{ form_row(form.file) }}
                    <div class="control-group">
                        {{ form_label(form.permissions) }}

                        <a href="#" id="add-another-perm" class="btn btn-info">Añadir un nuevo permiso</a>
                        <div id="perm-fields-list" data-prototype="{{ form_widget(form.permissions.vars.prototype) | e }}">
                            {% for emailField in form.permissions %}
                                <div class="span4">

                                    {{ form_errors(emailField) }}
                                    {{ form_widget(emailField) }}

                                </div>
                            {% endfor %}
                        </div>
                        {{ form_widget(form.permissions) }}

                    </div>

                    <div style="clear:both"></div>
                    {{ form_widget(form) }}



                </div>
            </div>
        </fieldset>
        <div style="text-align: center">
            <input type="submit" class="btn btn-success" value="Subir archivo">
        </div>
    </form>


</div>
<div id="content_uploader_success" style="display:none">
    <div class="alert alert-info">Archivo transferido correctamente</div>
</div>

<div id="content_uploader_success" style="display:none">
    <div class="alert alert-info">El archivo no pudo transferirse</div>
</div>


<script type="text/javascript">
    // keep track of how many email fields have been rendered
    var emailCount = '{{ form.permissions | length }}';

    jQuery(document).ready(function($) {

        $('#add-another-perm').click(function () {
            var emailList = jQuery('#perm-fields-list');

            // grab the prototype template
            var newWidget = emailList.attr('data-prototype');
            // replace the "__name__" used in the id and name of the prototype
            // with a number that's unique to your emails
            // end name attribute looks like name="contact[emails][2]"
            newWidget = newWidget.replace(/__name__/g, emailCount);


            // create a new list element and add it to the list
            var newLi = jQuery('<div class="span4"></div>').html(newWidget);
            newLi.appendTo(jQuery('#perm-fields-list'));
            var $field =$("#core_fileserverbundle_filetype_permissions_"+emailCount+"_user");

            $field.select2({"placeholder":"Select a value","allowClear":false,"minimumInputLength":0,"width":"element"});
            emailCount++;
            return false;
        });

        {% if redirect == 'ajax' %}

        $('#form_upload').submit(function () {

            console.log($(this));

            $.post("{{ path('core_fileserver_uploader', {'redirect': 'ajax'}) }}", $(this).serialize(),
                    function(data){

                        if(data == 'Ok'){
                            toastr['success']('Archivo subido correctamente');
                            $("#content_uploader").css('visibility', 'hidden');
                        }else{
                            toastr['error']('Error al subir el archivo');
                            $("#content_uploader").css('visibility', 'hidden');
                        }

                        return false;
                    });
            return false;
            /*
            $.ajax({
                type: "POST",
                url: "",
                data: $(this).serialize(),
                success: function (response) {
                    if (response == 'Ok') {

                        toastr['success']('Archivo subido correctamente');
                        $("#content_uploader").css('display', 'none');
                        $("#content_uploader_success").fadeIn();
                        return false
                    } else {
                        toastr['error']('Error al subir el archivo');
                        $("#content_uploader").css('display', 'none');
                        $("#content_uploader_success").fadeIn();
                        return false;
                    }

                },
                error: function () {

                    return false;
                }
                dataType: 'json'
            });


            return false;
            */
        });

        {% endif %}

    });
</script>